# Railway Deployment Configuration
[build]
  builder = "nixpacks"

[deploy]
  startCommand = "uvicorn simple_fastapi:app --host 0.0.0.0 --port ${PORT:-8000}"

[build.env]
  NIXPACKS_PYTHON_VERSION = "3.10"